const data = {
  products: [
    {
      name: "produit 1",
      price: 10,
      stock: 3,
      category: "categorie 1",
      mark: "Puma",
      image: "/images/cherries.jpg",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
    {
      name: "produit 2",
      price: 100,
      stock: 3,
      mark: "Jordan",
      category: "categorie 2",
      image: "/images/computer-mouse.png",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
    {
      name: "produit 3",
      price: 360,
      stock: 3,
      mark: "Nike",
      category: "categorie 3",
      image: "/images/cowboy-hat.png",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
    {
      name: "produit 4",
      price: 400,
      stock: 3,
      mark: "Jodan",
      category: "categorie 4",
      image: "/images/laptop.png",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
    {
      name: "produit 5",
      price: 100,
      stock: 3,
      mark: "Puma",
      category: "categorie 5",
      image: "/images/man1.png",
      rating: 3.4,
      description: "Bon produit",
    },
    {
      name: "produit 6",
      price: 100,
      stock: 3,
      mark: "Puma",
      category: "categorie 5",
      image: "/images/man.png",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
    {
      name: "produit 7",
      price: 100,
      stock: 3,
      mark: "Nike",
      category: "categorie 5",
      image: "/images/shoes-nike.jpg",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
    {
      name: "produit 8",
      price: 100,
      stock: 3,
      mark: "Nike",
      category: "categorie 5",
      image: "/images/shoes.png",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
    {
      name: "produit 9",
      price: 100,
      stock: 3,
      mark: "Nike",
      category: "categorie 5",
      image: "/images/statut.jpg",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
    {
      name: "produit 10",
      price: 100,
      stock: 3,
      mark: "Nike",
      category: "categorie 5",
      image: "/images/wrist-watch.jpg",
      rating: 3.4,
      description: "Bon produit",
      reviews: 10,
    },
  ],
};

export default data;
